Apply Lables from Other Repo in assignHasFixLabel()
eventespresso/actions pull request #53
Opened 2023-10-03 20:39 UTC by tn3rb

After making changes to https://github.com/eventespresso/barista/pull/1251
the Auto PR Labeler workflow ran but encountered the following error:
https://github.com/eventespresso/barista/actions/runs/6397687054/job/17366172149?pr=1251

![image](https://github.com/eventespresso/actions/assets/1751030/50e26f99-4698-47c3-aeed-db9475f16837)

which happened because PR 1251 references an issue from cafe via "closing text" in the original post:

> Fixes https://github.com/eventespresso/cafe/issues/816

and we are trying to apply the "has fix" label to that issue.

The error arises because the Auto PR Labeler action was initially set up with the assumption that all labels would belong to the same repo. But since Barista PR 1251 references Cafe Issue 816, we can't apply the Barista Has Fix label, and instead need to apply the Cafe Has Fix label.

This PR attempts to fix this by applying the other repo's label if the first attempt fails.
There's probably a more smarterer way to do this, but this was fastest to implement.

2023-10-04 10:16 UTC, alexkuc requested changes
Noticed a small issue with type, added suggestions directly to PR.

Another thing, I believe this PR could benefit from narrowing type of `RepoName`. Here's my proposed changes:

[narrow-type-RepoName.patch](https://github.com/eventespresso/actions/files/12802187/narrow-type-RepoName.patch)

To apply it, run this command from the root of the repo:
```shell
git patch apply narrow-type-RepoName.patch
```

I have checked this locally by running
```shell
yarn workspace @eventespresso-actions/auto-pr-labeler all
```

everything passed, no errors.

Why bother with narrowing the type? Well, since input can be any arbitrary string, it is possible to make a minor typo like `cafe ` where an extra space was added. With type narrowing and runtime validation, we can guard against issues like these.

2023-10-04 10:16 UTC, alexkuc commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
```suggestion
 * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | false>
```

2023-10-04 10:16 UTC, alexkuc commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
```suggestion
): Promise<GraphQlQueryResponse<LabelsQueryResponse> | false> => {
```

2023-10-31 16:14 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @param repoLabels RepoLabels
forgot to update after a change

2023-10-31 16:25 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:25 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:25 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-10-31 16:26 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-10-31 16:26 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | string>
thnx, applied

2023-10-31 16:26 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:26 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-10-31 16:26 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | string | boolean> => {
thnx, applied

2023-10-31 16:26 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-10-31 16:26 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:27 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:27 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-10-31 16:27 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:27 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-10-31 16:27 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-10-31 16:27 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-10-31 16:27 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:28 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-10-31 16:28 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:28 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | string | boolean> => {
thnx, applied

2023-10-31 16:28 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-10-31 16:28 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:28 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:28 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> + * @returns Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean>
thnx, applied

2023-10-31 16:29 UTC, tn3rb commented on packages/auto-pr-labeler/src/assignLabels.ts
> +): Promise<GraphQlQueryResponse<LabelsQueryResponse> | boolean> => {
thnx, applied

2023-11-02 18:15 UTC, alexkuc approved these changes
Awesome! 🎸

2024-05-14 23:00 UTC, merged